# Generated by Django 5.1.6 on 2025-02-25 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pno", models.CharField(max_length=50)),
                ("add", models.CharField(max_length=50)),
                (
                    "cource",
                    models.CharField(
                        choices=[
                            (
                                "Python FullStack Developement",
                                "Python FullStack Developement",
                            ),
                            (
                                "Java FullStack Developement",
                                "Java FullStack Developement",
                            ),
                            (
                                "MERN FullStack Developement",
                                "MERN FullStack Developement",
                            ),
                            ("FullStack Testing", "FullStack Testing"),
                        ],
                        default="Python FullStack Developement",
                        max_length=50,
                    ),
                ),
                ("profile_pic", models.ImageField(upload_to="student_profiles/")),
                (
                    "resume",
                    models.FileField(
                        upload_to="student_resumes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
